export * as Auth from './auth.js';
export * as Role from './role.js';
export * as Subject from './subject.js';
export * as Teacher from './teacher.js';
export * as WorkTime from './worktime.js';
export * as Student from './student.js';
export * as Ticket from './ticket.js';
export * as Lesson from './lesson.js';
export * as PayAccount from './payAccount.js';